FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN git clone https://github.com/trochepablo/LaboRedesySO.git /usr/src/app/appNode

WORKDIR /usr/src/app/appNode

RUN npm install
EXPOSE 8080

CMD ["npm","start"]

