FROM node:argon

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apk add --no-cache git
RUN apk add --no-cache openssh
RUN git clone https://github.com/trochepablo/LaboRedesySO.git /usr/src/app/appNode

RUN npm install
EXPOSE 8080

CMD ["npm","start"]

